<div class="container"><hr /></div>

<footer id="footer">
  <h2>Get A Quote</h2>
  <a href="/quote" class="button">Request</a>
  <div>
    <a href="http://www.houzz.com/pro/tqburns/ground-effects-landscaping">Houzz</a>
    &bull;
    <a href="https://www.facebook.com/Ground-Effects-Landscaping-161070937278668">Facebook</a>
    &bull;
    <a href="https://www.instagram.com/groundefx/">Instagram</a>
  </div>
</footer>

<!-- JavaScript -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- The core Firebase JS SDK is always required and must be listed first --><script src="/__/firebase/8.3.1/firebase-app.js"></script><!-- TODO: Add SDKs for Firebase products that you want to use     https://firebase.google.com/docs/web/setup#available-libraries --><script src="/__/firebase/8.3.1/firebase-analytics.js"></script><!-- Initialize Firebase --><script src="/__/firebase/init.js"></script>